name: CI/CD Build and Update GitOps

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'       # Only trigger when changes are made to the source code
      - 'infra/k8s/**' # Or if you change something in the chart

permissions:
  contents: write # Necessary for the bot to edit the values.yaml

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          # We use the commit SHA as the tag so that each version is unique
          IMAGE_TAG=${{ github.sha }}
          IMAGE_NAME=${{ secrets.ACR_NAME }}.azurecr.io/appfastapi:${{ github.sha }}
          
          docker build -t $IMAGE_NAME ./src
          docker push $IMAGE_NAME

      - name: Update Helm Chart with New Image Tag
        run: |
          # Install yq to easily edit the YAML
          sudo wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/bin/yq && sudo chmod +x /usr/bin/yq
          
          # Edit the image tag in the Helm values file
          yq -i ".image.tag = \"${{ github.sha }}\"" infra/k8s/appfastapi/values.yaml
          
      - name: Commit and Push changes to Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add infra/k8s/appfastapi/values.yaml
          git commit -m "chore: update image tag to ${{ github.sha }} [skip ci]"
          git push origin master